### PR TITLE
Initial action implemention

### PR DESCRIPTION
**Pull request by omus**
Implements a working solution for capturing output from all jobs in a matrix. See https://github.com/orgs/community/discussions/26639 for general discussion on this GitHub issue.

See the `design.md` file for details on the implementation details and design decisions behind this action.

Depends on:
- https://github.com/beacon-biosignals/job-context/pull/1

### CODE REVIEW

**Comment by omus** [comment]
I noticed if you re-run a job you can end up finding more artifacts than the `strategy.job-total`. This detection scenario seems flawed in that multiple re-runs could result in us falsely believing all the jobs had completed when in fact we may have not successfully run one of the jobs. I've now dropped the artifact count logic.

https://github.com/beacon-biosignals/matrix-output/actions/runs/10376312018/job/28728003750#step:3:54

**Comment by omus** [comment]
Looks like I got a natural race condition on "Setup Complex" https://github.com/beacon-biosignals/matrix-output/actions/runs/10376653588/job/28729096768?pr=1 just after I added the artificial race condition test.

**Comment by omus** [comment]
Checkout is causing me grief now:
```
Error: Repository path '/home/runner/work/_actions/beacon-biosignals/matrix-output/466c693173d9d5b623e6125d66afb817477e5a83/job-context/repo' is not under '/home/runner/work/matrix-output/matrix-output'
```

– https://github.com/beacon-biosignals/matrix-output/actions/runs/10377452845/job/28731668322?pr=1

**Comment by omus** [comment]
Much closer now. We have good matrix job detection working. The last workflow for "Setup Simple" end up selecting job as the job to wait which failed to wait as it had an incomplete artifact listing.

**Comment by omus** [comment]
Just fixed a bug where when two jobs wait for each other they weren't finding their sync artifacts due to comparing a numeric value with string in `jq`: https://github.com/beacon-biosignals/matrix-output/actions/runs/10414887856/job/28844541439?pr=1

I'm rather glad I hit this minor bug has it demonstrated that is possible for two jobs to have a complete set of outputs. Previously, this was just a theoretical problem.

**Review by MKVatinyan — APPROVED** [review]

**Pull request merged**
